export type Country = {
  code: string;
  flag: string;
  name: { ru: string; ky: string; en: string };
};

export const COUNTRIES: Country[] = [
  { code: "kg", flag: "🇰🇬", name: { ru: "Кыргызстан", ky: "Кыргызстан", en: "Kyrgyzstan" } },
  { code: "kz", flag: "🇰🇿", name: { ru: "Казахстан", ky: "Казакстан", en: "Kazakhstan" } },
  { code: "uz", flag: "🇺🇿", name: { ru: "Узбекистан", ky: "Өзбекстан", en: "Uzbekistan" } },
  { code: "tj", flag: "🇹🇯", name: { ru: "Таджикистан", ky: "Тажикстан", en: "Tajikistan" } },
  { code: "tm", flag: "🇹🇲", name: { ru: "Туркменистан", ky: "Түркмөнстан", en: "Turkmenistan" } },
  { code: "ru", flag: "🇷🇺", name: { ru: "Россия", ky: "Орусия", en: "Russia" } },
  { code: "by", flag: "🇧🇾", name: { ru: "Беларусь", ky: "Беларусь", en: "Belarus" } },
  { code: "ua", flag: "🇺🇦", name: { ru: "Украина", ky: "Украина", en: "Ukraine" } },
  { code: "md", flag: "🇲🇩", name: { ru: "Молдова", ky: "Молдова", en: "Moldova" } },
  { code: "ge", flag: "🇬🇪", name: { ru: "Грузия", ky: "Грузия", en: "Georgia" } },
  { code: "am", flag: "🇦🇲", name: { ru: "Армения", ky: "Армения", en: "Armenia" } },
  { code: "az", flag: "🇦🇿", name: { ru: "Азербайджан", ky: "Азербайжан", en: "Azerbaijan" } },
  { code: "us", flag: "🇺🇸", name: { ru: "США", ky: "АКШ", en: "United States" } },
  { code: "ca", flag: "🇨🇦", name: { ru: "Канада", ky: "Канада", en: "Canada" } },
  { code: "mx", flag: "🇲🇽", name: { ru: "Мексика", ky: "Мексика", en: "Mexico" } },
  { code: "br", flag: "🇧🇷", name: { ru: "Бразилия", ky: "Бразилия", en: "Brazil" } },
  { code: "ar", flag: "🇦🇷", name: { ru: "Аргентина", ky: "Аргентина", en: "Argentina" } },
  { code: "cl", flag: "🇨🇱", name: { ru: "Чили", ky: "Чили", en: "Chile" } },
  { code: "co", flag: "🇨🇴", name: { ru: "Колумбия", ky: "Колумбия", en: "Colombia" } },
  { code: "pe", flag: "🇵🇪", name: { ru: "Перу", ky: "Перу", en: "Peru" } },
  { code: "uy", flag: "🇺🇾", name: { ru: "Уругвай", ky: "Уругвай", en: "Uruguay" } },
  { code: "ve", flag: "🇻🇪", name: { ru: "Венесуэла", ky: "Венесуэла", en: "Venezuela" } },
  { code: "ec", flag: "🇪🇨", name: { ru: "Эквадор", ky: "Эквадор", en: "Ecuador" } },
  { code: "bo", flag: "🇧🇴", name: { ru: "Боливия", ky: "Боливия", en: "Bolivia" } },
  { code: "py", flag: "🇵🇾", name: { ru: "Парагвай", ky: "Парагвай", en: "Paraguay" } },
  { code: "cr", flag: "🇨🇷", name: { ru: "Коста-Рика", ky: "Коста-Рика", en: "Costa Rica" } },
  { code: "pa", flag: "🇵🇦", name: { ru: "Панама", ky: "Панама", en: "Panama" } },
  { code: "cu", flag: "🇨🇺", name: { ru: "Куба", ky: "Куба", en: "Cuba" } },
  { code: "do", flag: "🇩🇴", name: { ru: "Доминиканская Республика", ky: "Доминикан Республикасы", en: "Dominican Republic" } },
  { code: "gt", flag: "🇬🇹", name: { ru: "Гватемала", ky: "Гватемала", en: "Guatemala" } },
  { code: "hn", flag: "🇭🇳", name: { ru: "Гондурас", ky: "Гондурас", en: "Honduras" } },
  { code: "ni", flag: "🇳🇮", name: { ru: "Никарагуа", ky: "Никарагуа", en: "Nicaragua" } },
  { code: "sv", flag: "🇸🇻", name: { ru: "Сальвадор", ky: "Сальвадор", en: "El Salvador" } },
  { code: "jm", flag: "🇯🇲", name: { ru: "Ямайка", ky: "Ямайка", en: "Jamaica" } },
  { code: "ht", flag: "🇭🇹", name: { ru: "Гаити", ky: "Гаити", en: "Haiti" } },
  { code: "tt", flag: "🇹🇹", name: { ru: "Тринидад и Тобаго", ky: "Тринидад жана Тобаго", en: "Trinidad and Tobago" } },
  { code: "gb", flag: "🇬🇧", name: { ru: "Великобритания", ky: "Улуу Британия", en: "United Kingdom" } },
  { code: "ie", flag: "🇮🇪", name: { ru: "Ирландия", ky: "Ирландия", en: "Ireland" } },
  { code: "de", flag: "🇩🇪", name: { ru: "Германия", ky: "Германия", en: "Germany" } },
  { code: "fr", flag: "🇫🇷", name: { ru: "Франция", ky: "Франция", en: "France" } },
  { code: "es", flag: "🇪🇸", name: { ru: "Испания", ky: "Испания", en: "Spain" } },
  { code: "it", flag: "🇮🇹", name: { ru: "Италия", ky: "Италия", en: "Italy" } },
  { code: "pt", flag: "🇵🇹", name: { ru: "Португалия", ky: "Португалия", en: "Portugal" } },
  { code: "nl", flag: "🇳🇱", name: { ru: "Нидерланды", ky: "Нидерланд", en: "Netherlands" } },
  { code: "be", flag: "🇧🇪", name: { ru: "Бельгия", ky: "Бельгия", en: "Belgium" } },
  { code: "lu", flag: "🇱🇺", name: { ru: "Люксембург", ky: "Люксембург", en: "Luxembourg" } },
  { code: "ch", flag: "🇨🇭", name: { ru: "Швейцария", ky: "Швейцария", en: "Switzerland" } },
  { code: "at", flag: "🇦🇹", name: { ru: "Австрия", ky: "Австрия", en: "Austria" } },
  { code: "pl", flag: "🇵🇱", name: { ru: "Польша", ky: "Польша", en: "Poland" } },
  { code: "cz", flag: "🇨🇿", name: { ru: "Чехия", ky: "Чехия", en: "Czechia" } },
  { code: "sk", flag: "🇸🇰", name: { ru: "Словакия", ky: "Словакия", en: "Slovakia" } },
  { code: "hu", flag: "🇭🇺", name: { ru: "Венгрия", ky: "Венгрия", en: "Hungary" } },
  { code: "ro", flag: "🇷🇴", name: { ru: "Румыния", ky: "Румыния", en: "Romania" } },
  { code: "bg", flag: "🇧🇬", name: { ru: "Болгария", ky: "Болгария", en: "Bulgaria" } },
  { code: "rs", flag: "🇷🇸", name: { ru: "Сербия", ky: "Сербия", en: "Serbia" } },
  { code: "hr", flag: "🇭🇷", name: { ru: "Хорватия", ky: "Хорватия", en: "Croatia" } },
  { code: "si", flag: "🇸🇮", name: { ru: "Словения", ky: "Словения", en: "Slovenia" } },
  { code: "ba", flag: "🇧🇦", name: { ru: "Босния и Герцеговина", ky: "Босния жана Герцеговина", en: "Bosnia and Herzegovina" } },
  { code: "mk", flag: "🇲🇰", name: { ru: "Северная Македония", ky: "Түндүк Македония", en: "North Macedonia" } },
  { code: "me", flag: "🇲🇪", name: { ru: "Черногория", ky: "Черногория", en: "Montenegro" } },
  { code: "al", flag: "🇦🇱", name: { ru: "Албания", ky: "Албания", en: "Albania" } },
  { code: "xk", flag: "🇽🇰", name: { ru: "Косово", ky: "Косово", en: "Kosovo" } },
  { code: "gr", flag: "🇬🇷", name: { ru: "Греция", ky: "Греция", en: "Greece" } },
  { code: "cy", flag: "🇨🇾", name: { ru: "Кипр", ky: "Кипр", en: "Cyprus" } },
  { code: "mt", flag: "🇲🇹", name: { ru: "Мальта", ky: "Мальта", en: "Malta" } },
  { code: "se", flag: "🇸🇪", name: { ru: "Швеция", ky: "Швеция", en: "Sweden" } },
  { code: "no", flag: "🇳🇴", name: { ru: "Норвегия", ky: "Норвегия", en: "Norway" } },
  { code: "fi", flag: "🇫🇮", name: { ru: "Финляндия", ky: "Финляндия", en: "Finland" } },
  { code: "dk", flag: "🇩🇰", name: { ru: "Дания", ky: "Дания", en: "Denmark" } },
  { code: "is", flag: "🇮🇸", name: { ru: "Исландия", ky: "Исландия", en: "Iceland" } },
  { code: "ee", flag: "🇪🇪", name: { ru: "Эстония", ky: "Эстония", en: "Estonia" } },
  { code: "lv", flag: "🇱🇻", name: { ru: "Латвия", ky: "Латвия", en: "Latvia" } },
  { code: "lt", flag: "🇱🇹", name: { ru: "Литва", ky: "Литва", en: "Lithuania" } },
  { code: "tr", flag: "🇹🇷", name: { ru: "Турция", ky: "Түркия", en: "Türkiye" } },
  { code: "il", flag: "🇮🇱", name: { ru: "Израиль", ky: "Израиль", en: "Israel" } },
  { code: "ps", flag: "🇵🇸", name: { ru: "Палестина", ky: "Палестина", en: "Palestine" } },
  { code: "sa", flag: "🇸🇦", name: { ru: "Саудовская Аравия", ky: "Сауд Арабиясы", en: "Saudi Arabia" } },
  { code: "ae", flag: "🇦🇪", name: { ru: "ОАЭ", ky: "БАЭ", en: "United Arab Emirates" } },
  { code: "qa", flag: "🇶🇦", name: { ru: "Катар", ky: "Катар", en: "Qatar" } },
  { code: "kw", flag: "🇰🇼", name: { ru: "Кувейт", ky: "Кувейт", en: "Kuwait" } },
  { code: "bh", flag: "🇧🇭", name: { ru: "Бахрейн", ky: "Бахрейн", en: "Bahrain" } },
  { code: "om", flag: "🇴🇲", name: { ru: "Оман", ky: "Оман", en: "Oman" } },
  { code: "ye", flag: "🇾🇪", name: { ru: "Йемен", ky: "Йемен", en: "Yemen" } },
  { code: "jo", flag: "🇯🇴", name: { ru: "Иордания", ky: "Иордания", en: "Jordan" } },
  { code: "lb", flag: "🇱🇧", name: { ru: "Ливан", ky: "Ливан", en: "Lebanon" } },
  { code: "sy", flag: "🇸🇾", name: { ru: "Сирия", ky: "Сирия", en: "Syria" } },
  { code: "iq", flag: "🇮🇶", name: { ru: "Ирак", ky: "Ирак", en: "Iraq" } },
  { code: "ir", flag: "🇮🇷", name: { ru: "Иран", ky: "Иран", en: "Iran" } },
  { code: "af", flag: "🇦🇫", name: { ru: "Афганистан", ky: "Ооганстан", en: "Afghanistan" } },
  { code: "pk", flag: "🇵🇰", name: { ru: "Пакистан", ky: "Пакистан", en: "Pakistan" } },
  { code: "in", flag: "🇮🇳", name: { ru: "Индия", ky: "Индия", en: "India" } },
  { code: "bd", flag: "🇧🇩", name: { ru: "Бангладеш", ky: "Бангладеш", en: "Bangladesh" } },
  { code: "lk", flag: "🇱🇰", name: { ru: "Шри-Ланка", ky: "Шри-Ланка", en: "Sri Lanka" } },
  { code: "np", flag: "🇳🇵", name: { ru: "Непал", ky: "Непал", en: "Nepal" } },
  { code: "bt", flag: "🇧🇹", name: { ru: "Бутан", ky: "Бутан", en: "Bhutan" } },
  { code: "mv", flag: "🇲🇻", name: { ru: "Мальдивы", ky: "Мальдив аралдары", en: "Maldives" } },
  { code: "mn", flag: "🇲🇳", name: { ru: "Монголия", ky: "Монголия", en: "Mongolia" } },
  { code: "cn", flag: "🇨🇳", name: { ru: "Китай", ky: "Кытай", en: "China" } },
  { code: "hk", flag: "🇭🇰", name: { ru: "Гонконг", ky: "Гонконг", en: "Hong Kong" } },
  { code: "tw", flag: "🇹🇼", name: { ru: "Тайвань", ky: "Тайвань", en: "Taiwan" } },
  { code: "mo", flag: "🇲🇴", name: { ru: "Макао", ky: "Макао", en: "Macao" } },
  { code: "jp", flag: "🇯🇵", name: { ru: "Япония", ky: "Япония", en: "Japan" } },
  { code: "kr", flag: "🇰🇷", name: { ru: "Южная Корея", ky: "Түштүк Корея", en: "South Korea" } },
  { code: "kp", flag: "🇰🇵", name: { ru: "Северная Корея", ky: "Түндүк Корея", en: "North Korea" } },
  { code: "vn", flag: "🇻🇳", name: { ru: "Вьетнам", ky: "Вьетнам", en: "Vietnam" } },
  { code: "th", flag: "🇹🇭", name: { ru: "Таиланд", ky: "Таиланд", en: "Thailand" } },
  { code: "la", flag: "🇱🇦", name: { ru: "Лаос", ky: "Лаос", en: "Laos" } },
  { code: "kh", flag: "🇰🇭", name: { ru: "Камбоджа", ky: "Камбоджа", en: "Cambodia" } },
  { code: "mm", flag: "🇲🇲", name: { ru: "Мьянма", ky: "Мьянма", en: "Myanmar" } },
  { code: "my", flag: "🇲🇾", name: { ru: "Малайзия", ky: "Малайзия", en: "Malaysia" } },
  { code: "sg", flag: "🇸🇬", name: { ru: "Сингапур", ky: "Сингапур", en: "Singapore" } },
  { code: "id", flag: "🇮🇩", name: { ru: "Индонезия", ky: "Индонезия", en: "Indonesia" } },
  { code: "ph", flag: "🇵🇭", name: { ru: "Филиппины", ky: "Филиппиндер", en: "Philippines" } },
  { code: "bn", flag: "🇧🇳", name: { ru: "Бруней", ky: "Бруней", en: "Brunei" } },
  { code: "tl", flag: "🇹🇱", name: { ru: "Восточный Тимор", ky: "Чыгыш Тимор", en: "Timor-Leste" } },
  { code: "au", flag: "🇦🇺", name: { ru: "Австралия", ky: "Австралия", en: "Australia" } },
  { code: "nz", flag: "🇳🇿", name: { ru: "Новая Зеландия", ky: "Жаңы Зеландия", en: "New Zealand" } },
  { code: "fj", flag: "🇫🇯", name: { ru: "Фиджи", ky: "Фиджи", en: "Fiji" } },
  { code: "pg", flag: "🇵🇬", name: { ru: "Папуа — Новая Гвинея", ky: "Папуа — Жаңы Гвинея", en: "Papua New Guinea" } },
  { code: "ws", flag: "🇼🇸", name: { ru: "Самоа", ky: "Самоа", en: "Samoa" } },
  { code: "to", flag: "🇹🇴", name: { ru: "Тонга", ky: "Тонга", en: "Tonga" } },
  { code: "vu", flag: "🇻🇺", name: { ru: "Вануату", ky: "Вануату", en: "Vanuatu" } },
  { code: "sb", flag: "🇸🇧", name: { ru: "Соломоновы Острова", ky: "Соломон аралдары", en: "Solomon Islands" } },
  { code: "eg", flag: "🇪🇬", name: { ru: "Египет", ky: "Египет", en: "Egypt" } },
  { code: "ma", flag: "🇲🇦", name: { ru: "Марокко", ky: "Марокко", en: "Morocco" } },
  { code: "dz", flag: "🇩🇿", name: { ru: "Алжир", ky: "Алжир", en: "Algeria" } },
  { code: "tn", flag: "🇹🇳", name: { ru: "Тунис", ky: "Тунис", en: "Tunisia" } },
  { code: "ly", flag: "🇱🇾", name: { ru: "Ливия", ky: "Ливия", en: "Libya" } },
  { code: "sd", flag: "🇸🇩", name: { ru: "Судан", ky: "Судан", en: "Sudan" } },
  { code: "ng", flag: "🇳🇬", name: { ru: "Нигерия", ky: "Нигерия", en: "Nigeria" } },
  { code: "za", flag: "🇿🇦", name: { ru: "ЮАР", ky: "ТАР", en: "South Africa" } },
  { code: "ke", flag: "🇰🇪", name: { ru: "Кения", ky: "Кения", en: "Kenya" } },
  { code: "et", flag: "🇪🇹", name: { ru: "Эфиопия", ky: "Эфиопия", en: "Ethiopia" } },
  { code: "gh", flag: "🇬🇭", name: { ru: "Гана", ky: "Гана", en: "Ghana" } },
  { code: "ci", flag: "🇨🇮", name: { ru: "Кот-д'Ивуар", ky: "Кот-д'Ивуар", en: "Côte d'Ivoire" } },
  { code: "sn", flag: "🇸🇳", name: { ru: "Сенегал", ky: "Сенегал", en: "Senegal" } },
  { code: "tz", flag: "🇹🇿", name: { ru: "Танзания", ky: "Танзания", en: "Tanzania" } },
  { code: "ug", flag: "🇺🇬", name: { ru: "Уганда", ky: "Уганда", en: "Uganda" } },
  { code: "rw", flag: "🇷🇼", name: { ru: "Руанда", ky: "Руанда", en: "Rwanda" } },
  { code: "zm", flag: "🇿🇲", name: { ru: "Замбия", ky: "Замбия", en: "Zambia" } },
  { code: "zw", flag: "🇿🇼", name: { ru: "Зимбабве", ky: "Зимбабве", en: "Zimbabwe" } },
  { code: "ao", flag: "🇦🇴", name: { ru: "Ангола", ky: "Ангола", en: "Angola" } },
  { code: "mz", flag: "🇲🇿", name: { ru: "Мозамбик", ky: "Мозамбик", en: "Mozambique" } },
  { code: "mg", flag: "🇲🇬", name: { ru: "Мадагаскар", ky: "Мадагаскар", en: "Madagascar" } },
  { code: "mu", flag: "🇲🇺", name: { ru: "Маврикий", ky: "Маврикий", en: "Mauritius" } },
  { code: "cm", flag: "🇨🇲", name: { ru: "Камерун", ky: "Камерун", en: "Cameroon" } },
  { code: "bf", flag: "🇧🇫", name: { ru: "Буркина-Фасо", ky: "Буркина-Фасо", en: "Burkina Faso" } },
  { code: "ml", flag: "🇲🇱", name: { ru: "Мали", ky: "Мали", en: "Mali" } },
  { code: "ne", flag: "🇳🇪", name: { ru: "Нигер", ky: "Нигер", en: "Niger" } },
  { code: "td", flag: "🇹🇩", name: { ru: "Чад", ky: "Чад", en: "Chad" } },
  { code: "so", flag: "🇸🇴", name: { ru: "Сомали", ky: "Сомали", en: "Somalia" } },
  { code: "er", flag: "🇪🇷", name: { ru: "Эритрея", ky: "Эритрея", en: "Eritrea" } },
  { code: "dj", flag: "🇩🇯", name: { ru: "Джибути", ky: "Джибути", en: "Djibouti" } },
  { code: "ga", flag: "🇬🇦", name: { ru: "Габон", ky: "Габон", en: "Gabon" } },
  { code: "cg", flag: "🇨🇬", name: { ru: "Республика Конго", ky: "Конго Республикасы", en: "Republic of the Congo" } },
  { code: "cd", flag: "🇨🇩", name: { ru: "ДР Конго", ky: "Конго ДР", en: "DR Congo" } },
];

export const COUNTRY_BY_FLAG: Record<string, Country> = Object.fromEntries(
  COUNTRIES.map((c) => [c.flag, c]),
);

export const COUNTRY_BY_CODE: Record<string, Country> = Object.fromEntries(
  COUNTRIES.map((c) => [c.code, c]),
);
